# Generated by Django 5.1.6 on 2025-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_note_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_focus',
            field=models.BooleanField(default=False),
        ),
    ]
