# Generated by Django 5.1.6 on 2025-06-07 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_focus',
        ),
    ]
